version: "3"
services:
    highoctane_blog:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: highoctane_blog
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        ports:
            - "8000:80"
        depends_on:
            - db
         
    db:
        image: "microsoft/mssql-server-linux"
        container_name: sqlserver
        ports: 
            - "1433:1433"
        environment:
            SA_PASSWORD: "Password1234@@"
            ACCEPT_EULA: "Y"
